"""init

Revision ID: 91ca9b05c106
Revises: 96f7c30be23d
Create Date: 2024-02-10 21:59:25.792843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ca9b05c106'
down_revision = '96f7c30be23d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###
